Update jekyll.yml

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -19,8 +19,26 @@ jobs:
           bundle install
           npm install
           npm run build
-      - uses: helaili/jekyll-action@2.0.4
+      - name: publish
+        # Derived from helaili/jekyll-action@2.0.4
         env:
           JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
-        with:
-          target_branch: 'gh-pages'
+        run: |
+          cd _site
+          
+          remote_branch=gh_pages
+          if [ "${GITHUB_REF}" = "refs/heads/${remote_branch}" ]; then
+            echo "::error::Cannot publish on branch ${remote_branch}"
+            exit 1
+          fi
+
+          echo "Publishing to ${GITHUB_REPOSITORY} on branch ${remote_branch}"
+          echo "::debug::Pushing to https://${JEKYLL_PAT}@github.com/${GITHUB_REPOSITORY}.git"
+
+          remote_repo="https://${JEKYLL_PAT}@github.com/${GITHUB_REPOSITORY}.git" && \
+          git init && \
+          git config user.name "${GITHUB_ACTOR}" && \
+          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
+          git add . && \
+          git commit -m "jekyll build from Action ${GITHUB_SHA}" && \
+          git push --force $remote_repo master:$remote_branch && \
